CREATE TABLE CLIENTS
(
    PHONE_NUMBER      CHAR(10)    NOT NULL,
    NAME              VARCHAR(50) NOT NULL,
    EMAIL             VARCHAR(30),
    LOCATION          VARCHAR(40),
    STAFF_WORK_NUMBER INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    AUTO_STORE_NAME   VARCHAR(20) NOT NULL,
    PRICE_AUTOMOBILE  DECIMAL(9, 2)

);



ALTER TABLE CLIENTS
    ADD CONSTRAINT PK_CLIENTS PRIMARY KEY (PHONE_NUMBER);

ALTER TABLE CLIENTS
    ADD CONSTRAINT FK_CLIENTS FOREIGN KEY (STAFF_WORK_NUMBER) REFERENCES STAFF (WORK_NUMBER);

ALTER TABLE CLIENTS
    ADD CONSTRAINT FK2_CLIENTS FOREIGN KEY (AUTO_STORE_NAME) REFERENCES AUTOSTORES (NAME);

ALTER TABLE CLIENTS
    ADD CONSTRAINT CK_EMAIL CHECK ( EMAIL LIKE '%_@_%.__%' );

CREATE TABLE STAFF
(
    WORK_NUMBER     INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME            VARCHAR(50) NOT NULL,
    PHONE_NUMBER    CHAR(10),
    REGION          VARCHAR(40),
    AUTO_STORE_NAME VARCHAR(20) NOT NULL,
    SERVICES_TYPE   VARCHAR(30) NOT NULL

);

ALTER TABLE STAFF
    ADD CONSTRAINT PK_STAFF PRIMARY KEY (WORK_NUMBER);

ALTER TABLE STAFF
    ADD CONSTRAINT FK_STAFF FOREIGN KEY (AUTO_STORE_NAME) REFERENCES AUTOSTORES (NAME);

ALTER TABLE STAFF
    ADD CONSTRAINT FK2_STAFF FOREIGN KEY (SERVICES_TYPE) REFERENCES SERVICES (TYPE);


CREATE TABLE CARS
(
    CLIENT_PHONE_NUMBER    CHAR(10)    NOT NULL,
    BRAND                  VARCHAR(20) NOT NULL,
    CATEGORY               VARCHAR(10) NOT NULL,
    PRICE                  FLOAT       NOT NULL,
    COLOUR                 VARCHAR(15),
    HORSEPOWER             INT,
    EURO_EMISSION_STANDARD SMALLINT,
    YEAR_MANUFACTURE       INT,
    ENGINE_TYPE            VARCHAR(10),
    TRANSMISSION_TYPE      VARCHAR(20),
    SPARE_TYRE             SMALLINT,
    SPOILER                SMALLINT,
    SUNROOF                SMALLINT

);

ALTER TABLE CARS
    ADD CONSTRAINT FK_CARS FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENTS (PHONE_NUMBER);

ALTER TABLE CARS
    ADD CONSTRAINT PK_CARS PRIMARY KEY (CLIENT_PHONE_NUMBER, BRAND);

ALTER TABLE CARS
    ADD CONSTRAINT CK_YEAR_MANUFACTURE_CARS CHECK (CARS.YEAR_MANUFACTURE > 2020);

ALTER TABLE CARS
    ADD CONSTRAINT CK_SPARE_TYRE_CARS CHECK (SPARE_TYRE IN (0, 1));

ALTER TABLE CARS
    ADD CONSTRAINT CK_SPOILER_CARS CHECK ( SPOILER IN (0, 1) );

ALTER TABLE CARS
    ADD CONSTRAINT CK_SUNROOF_CARS CHECK ( SUNROOF IN (0, 1) );

ALTER TABLE CARS
    ADD CONSTRAINT CK_EURO_EMISSION_STANDARD_CARS CHECK (CARS.EURO_EMISSION_STANDARD > 0);

ALTER TABLE CARS
    ADD CONSTRAINT CK_HORSEPOWER_CARS CHECK ( CARS.HORSEPOWER > 0 );

ALTER TABLE CARS
    ADD CONSTRAINT CK_ENGINE_TYPE_CARS CHECK (ENGINE_TYPE IN ('DIESEL', 'PETROL', 'HYBRID', 'ELECTRIC'));

ALTER TABLE CARS
    ADD CONSTRAINT CK_TRANSMISSION_TYPE_CARS CHECK (TRANSMISSION_TYPE IN ('AUTOMATIC', 'SEMI', 'MANUAL'));

CREATE TABLE TRUCKS
(
    CLIENT_PHONE_NUMBER    CHAR(10)    NOT NULL,
    BRAND                  VARCHAR(20) NOT NULL,
    CATEGORY               VARCHAR(10) NOT NULL,
    PRICE                  FLOAT       NOT NULL,
    COLOUR                 VARCHAR(15),
    HORSEPOWER             INT,
    EURO_EMISSION_STANDARD SMALLINT,
    YEAR_MANUFACTURE       INT,
    ENGINE_TYPE            VARCHAR(10),
    TRANSMISSION_TYPE      VARCHAR(20),
    SPARE_TYRE             SMALLINT,
    LOAD_CAPACITY          FLOAT,
    NUMBER_OF_AXLES        SMALLINT,
    NUMBER_OF_SEATS        SMALLINT

);

ALTER TABLE TRUCKS
    ADD CONSTRAINT FK_TRUCKS FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENTS (PHONE_NUMBER);


ALTER TABLE TRUCKS
    ADD CONSTRAINT PK_TRUCKS PRIMARY KEY (CLIENT_PHONE_NUMBER, BRAND);

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_YEAR_MANUFACTURE CHECK (TRUCKS.YEAR_MANUFACTURE > 2020);

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_SPARE_TYRE_TRUCKS CHECK (SPARE_TYRE IN (0, 1));

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_LOAD_CAPACITY_TRUCKS CHECK (LOAD_CAPACITY > 0);

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_NUMBER_OF_AXLES_TRUCKS CHECK (NUMBER_OF_AXLES > 0);

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_NUMBER_OF_SEATS_TRUCKS CHECK ( NUMBER_OF_SEATS > 0 );

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_EURO_EMISSION_STANDARD_TRUCKS CHECK (EURO_EMISSION_STANDARD > 0);

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_HORSEPOWER_TRUCKS CHECK ( HORSEPOWER > 0 );

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_ENGINE_TYPE_TRUCKS CHECK (ENGINE_TYPE IN ('DIESEL', 'PETROL', 'HYBRID', 'ELECTRIC'));

ALTER TABLE TRUCKS
    ADD CONSTRAINT CK_TRANSMISSION_TYPE_TRUCKS CHECK (TRANSMISSION_TYPE IN ('AUTOMATIC', 'SEMI', 'MANUAL'));

CREATE TABLE BUSES
(
    CLIENT_PHONE_NUMBER    CHAR(10)    NOT NULL,
    BRAND                  VARCHAR(20) NOT NULL,
    CATEGORY               VARCHAR(10) NOT NULL,
    PRICE                  FLOAT       NOT NULL,
    COLOUR                 VARCHAR(15),
    HORSEPOWER             INT,
    EURO_EMISSION_STANDARD SMALLINT,
    YEAR_MANUFACTURE       INT,
    ENGINE_TYPE            VARCHAR(10),
    TRANSMISSION_TYPE      VARCHAR(20),
    SPARE_TYRE             SMALLINT,
    SUNROOF                SMALLINT,
    LOAD_CAPACITY          FLOAT,
    NUMBER_OF_AXLES        SMALLINT,
    NUMBER_OF_SEATS        SMALLINT

);

ALTER TABLE BUSES
    ADD CONSTRAINT FK_BUSES FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENTS (PHONE_NUMBER);

ALTER TABLE BUSES
    ADD CONSTRAINT PK_BUSES PRIMARY KEY (CLIENT_PHONE_NUMBER, BRAND);

ALTER TABLE BUSES
    ADD CONSTRAINT CK_HORSEPOWER_BUSES CHECK ( BUSES.HORSEPOWER > 0 );


ALTER TABLE BUSES
    ADD CONSTRAINT CK_YEAR_MANUFACTURE_BUSES CHECK (BUSES.YEAR_MANUFACTURE > 2020);

ALTER TABLE BUSES
    ADD CONSTRAINT CK_SPARE_TYRE_BUSES CHECK (SPARE_TYRE IN (0, 1));

ALTER TABLE BUSES
    ADD CONSTRAINT CK_LOAD_CAPACITY_BUSES CHECK (LOAD_CAPACITY > 0);

ALTER TABLE BUSES
    ADD CONSTRAINT CK_NUMBER_OF_AXLES_BUSES CHECK (BUSES.NUMBER_OF_AXLES > 0);

ALTER TABLE BUSES
    ADD CONSTRAINT CK_NUMBER_OF_SEATS_BUSES CHECK ( BUSES.NUMBER_OF_SEATS > 0 );

ALTER TABLE BUSES
    ADD CONSTRAINT CK_EURO_EMISSION_STANDARD_BUSES CHECK (BUSES.EURO_EMISSION_STANDARD > 0);

ALTER TABLE BUSES
    ADD CONSTRAINT CK_SUNROOF_BUSES CHECK ( SUNROOF IN (0, 1) );

ALTER TABLE BUSES
    ADD CONSTRAINT CK_ENGINE_TYPE_BUSES CHECK (ENGINE_TYPE IN ('DIESEL', 'PETROL', 'HYBRID', 'ELECTRIC'));

ALTER TABLE BUSES
    ADD CONSTRAINT CK_TRANSMISSION_TYPE_BUSES CHECK (TRANSMISSION_TYPE IN ('AUTOMATIC', 'SEMI', 'MANUAL'));

CREATE TABLE AUTOSTORES
(
    NAME    VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(40)
);

ALTER TABLE AUTOSTORES
    ADD CONSTRAINT PK_AUTO_STORES PRIMARY KEY (NAME);


CREATE TABLE SERVICES
(
    TYPE  VARCHAR(30) NOT NULL,
    PRICE FLOAT
);

ALTER TABLE SERVICES
    ADD CONSTRAINT PK_SERVICES PRIMARY KEY (TYPE);


CREATE TABLE RECEIVES
(
    CLIENT_PHONE_NUMBER CHAR(10)    NOT NULL,
    SERVICES_TYPE       VARCHAR(30) NOT NULL
);


ALTER TABLE RECEIVES
    ADD CONSTRAINT FK_RECEIVES FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENTS (PHONE_NUMBER);

ALTER TABLE RECEIVES
    ADD CONSTRAINT FK2_RECEIVES FOREIGN KEY (SERVICES_TYPE) REFERENCES SERVICES (TYPE);

ALTER TABLE RECEIVES
    ADD CONSTRAINT PK_RECEIVES PRIMARY KEY (CLIENT_PHONE_NUMBER, SERVICES_TYPE);


CREATE TABLE REQUIRES
(
    CLIENT_PHONE_NUMBER CHAR(10)    NOT NULL,
    AUTO_STORE_NAME     VARCHAR(20) NOT NULL,
    TYPE_AUTOMOBILE     VARCHAR(50),
    MAX_PRICE           DECIMAL(9, 2)

);

ALTER TABLE REQUIRES
    ADD CONSTRAINT FK_REQUIRES FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENTS (PHONE_NUMBER);


ALTER TABLE REQUIRES
    ADD CONSTRAINT FK2_REQUIRES FOREIGN KEY (AUTO_STORE_NAME) REFERENCES AUTOSTORES (NAME);


ALTER TABLE REQUIRES
    ADD CONSTRAINT PK_REQUIRES PRIMARY KEY (CLIENT_PHONE_NUMBER, AUTO_STORE_NAME);

