CREATE TABLE DEPT
(
    DNO   CHAR(3) NOT NULL,
    DNAME VARCHAR(30),
    MGRNO CHAR(6)
);

CREATE TABLE EMP
(
    ENO       CHAR(6) NOT NULL,
    ENAME     VARCHAR(18),
    WORKDEPT  CHAR(3),
    HIREDATE  DATE,
    BIRTHDATE DATE,
    SALARY    DECIMAL(9, 2)
);

ALTER TABLE DEPT
    ADD CONSTRAINT PK_DNO PRIMARY KEY (DNO);

ALTER TABLE EMP
    ADD CONSTRAINT PK_ENO PRIMARY KEY (ENO);

ALTER TABLE EMP
    ADD CONSTRAINT FK_WORK_DEPT FOREIGN KEY (WORKDEPT) REFERENCES DEPT (DNO);

ALTER TABLE EMP
    ADD CONSTRAINT CK_SALARY CHECK (SALARY > 0);

SET SCHEMA DB2MOVIE;
SELECT NAME AS MOVIESTAR, GENDER AS GENDERSTAR, BIRTHDATE AS DATEOFBIRTH
FROM DB2MOVIE.MOVIESTAR
WHERE NAME LIKE 'J%'
  AND BIRTHDATE > '1948-01-01'
ORDER BY NAME DESC;

SET SCHEMA DB2SHIPS;
SELECT  C.BORE AS SHIPBORE, S.NAME AS SHIPNAME,S.LAUNCHED AS YEAROFLAUNCH
FROM CLASSES C,
     SHIPS S
WHERE C.CLASS = S.CLASS
  AND S.LAUNCHED < 1940;

SET SCHEMA DB2MOVIE;
SELECT M.NAME AS MOVIESTAR,M.ADDRESS AS STARADDRESS ,S.MOVIETITLE AS MOVIETITLE,MOVIEYEAR
FROM MOVIESTAR M,STARSIN S
WHERE M.NAME=S.STARNAME
      AND M.NAME LIKE 'J%'
AND MOVIEYEAR>1990
;
