SET SCHEMA DB2MOVIE;

SELECT NAME, GENDER, TITLE
FROM MOVIE,
     MOVIESTAR
WHERE TITLE = 'Terms of Endearment';

SELECT STARNAME, TITLE
FROM MOVIE,
     STARSIN
WHERE TITLE = MOVIETITLE
  AND YEAR = MOVIEYEAR
  AND STUDIONAME = 'MGM'
  AND YEAR = 1995;


SELECT ME.NAME, M.TITLE, M.STUDIONAME
FROM MOVIE M,
     MOVIEEXEC ME
WHERE M.PRODUCERC# = ME.CERT#
  AND M.STUDIONAME = 'MGM';

SELECT ALLM.TITLE, ALLM.LENGTH, GWTW.TITLE, GWTW.LENGTH
FROM MOVIE ALLM, MOVIE GWTW
WHERE GWTW.TITLE = 'Gone With the Wind'
AND ALLM.LENGTH > GWTW.LENGTH;




