SET SCHEMA MOVIES;

SELECT  PRESC#,PRESC#/2.0 AS PRESC2,PRESC# +3
FROM STUDIO
WHERE PRESC# = 1;

SELECT TITLE,YEAR,LENGTH,LENGTH/60 AS HOURS,MOD(LENGTH,60) AS MINUTES
FROM MOVIE
WHERE LENGTH>110;

--DISTINCTION OF THE DIFFERENT ONES
SELECT DISTINCT LENGTH/60 AS HOURS
FROM MOVIE
WHERE LENGTH>110;

--SELECT ALL
SELECT *
FROM MOVIE
WHERE LENGTH>110;

SELECT TITLE,YEAR
FROM MOVIE
WHERE STUDIONAME = 'Fox';

SELECT NAME
FROM MOVIESTAR
WHERE BIRTHDATE = '1977-07-06';

--NULL COMPARISON
SELECT TITLE,YEAR
FROM MOVIE
WHERE LENGTH IS NULL ;

--BETWEEN OPERATOR
SELECT TITLE,YEAR
FROM MOVIE
WHERE YEAR BETWEEN 1000 AND 1950;

--IN OPERATOR
SELECT TITLE,YEAR
FROM MOVIE
WHERE LENGTH IN (111,124) ;

--LIKE OPERATOR (SEEMS LIKE REGEX)
SELECT TITLE,YEAR
FROM MOVIE
WHERE TITLE LIKE 'St_r%';

--SORTING WITH ORDER BY
SELECT STUDIONAME,TITLE,LENGTH
FROM MOVIE
WHERE LENGTH>110
ORDER BY STUDIONAME ASC ;

--SIMPLE QUERIES FOR
SELECT ADDRESS
FROM STUDIO
WHERE NAME = 'MGM';

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'Sandra Bullock';

SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE = 'Love' AND MOVIEYEAR = '1980';

SELECT NAME,NETWORTH
FROM MOVIEEXEC
WHERE NETWORTH >10000000;

--SIMPLE QUERIES FOR SHIPS
SET SCHEMA SHIPS;

SELECT  CLASS,COUNTRY
FROM CLASSES
WHERE NUMGUNS<10;

SELECT NAME AS SHIPNAME,LAUNCHED
FROM SHIPS
WHERE LAUNCHED < 1918 ;

SELECT SHIP,BATTLE
FROM OUTCOMES
WHERE RESULT = 'sunk'
ORDER BY BATTLE;

SELECT NAME AS SHIPNAME
FROM SHIPS
WHERE NAME = CLASS;



SELECT NAME AS SHIPNAME
FROM SHIPS
WHERE NAME LIKE 'R%';

SELECT NAME AS SHIPNAME
FROM SHIPS
WHERE NAME LIKE '_% _%' AND NAME NOT LIKE '_% _% _%';

